file_size: 1000 # number of sequences / receptors per file as stored internally by ImmuneML in ImmuneML format - not visible to users
paired: True
separator: "\t"
misc:
  all_dual_chains: True
  all_genes: False
# todo separator can not be added here currently because alt. load func doesn't support parameters