paired: True # whether to load paired data: if true returns ReceptorDataset, and if false returns SequenceDataset
recursive: False # whether to search for tsv VDJdb files recursively down the path
file_size: 1000 # number of sequences / receptors per file as stored internally by ImmuneML in ImmuneML format - not visible to users